#! /bin/bash
#$ -S /bin/bash
#SBATCH -J 'q1_12_hba1c'
#SBATCH -D  /projects/kilpelainen-AUDIT/people/zlc436/answer_reviewer_5/output/2_haplotype_plot/2_clumped_data/clumped_data/qsub_files
module load gcc/11.2.0
module load R/4.3.1
Rscript /projects/kilpelainen-AUDIT/data/tools/ld_clump_1KG/code/internal/1_matching_1K_data_chr12.R /projects/kilpelainen-AUDIT/people/zlc436/answer_reviewer_5/code/2_ld_clumping/clumping_hba1c.cfg
