#! /bin/bash
#$ -S /bin/bash
#SBATCH -J 'q0_hba1c_hk1_nk2r_tspan15'
#SBATCH -D  /projects/kilpelainen-AUDIT/people/zlc436/answer_reviewer_5/output/2_haplotype_plot/3_fine_mapped_data//qsub_files
module load gcc/11.2.0
module load R/4.3.1
Rscript /projects/kilpelainen-AUDIT/data/tools/fine_mapping_carma/code/internal/0_setting_up_temporal_data.R /projects/kilpelainen-AUDIT/people/zlc436/answer_reviewer_5/code/3_fine_mapping/2_running_carma/1_carma_hba1c.cfg
