#! /bin/bash
#$ -S /bin/bash
#SBATCH -J 'q2_hba1c_hk1_nk2r_tspan15'
#SBATCH -D  /projects/kilpelainen-AUDIT/people/zlc436/answer_reviewer_5/output/2_haplotype_plot/3_fine_mapped_data//qsub_files
module load gcc/11.2.0
module load R/4.3.1
LD_PRELOAD=/opt/software/anaconda3/4.0.0/lib/libmkl_rt.so Rscript /projects/kilpelainen-AUDIT/data/tools/fine_mapping_carma/code/internal/2_running_carma.R /projects/kilpelainen-AUDIT/people/zlc436/answer_reviewer_5/code/3_fine_mapping/2_running_carma/1_carma_hba1c.cfg
